// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNuEYEmyPqa-2XNA_cHab1FGXMXrAwqkY',
    appId: '1:105046275678:web:64e17dbe2cb0776cc6a6cf',
    messagingSenderId: '105046275678',
    projectId: 'spotify101',
    authDomain: 'spotify101.firebaseapp.com',
    storageBucket: 'spotify101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVrMX5Y3esf2TGVMaug_fzY9fEzC--Thk',
    appId: '1:105046275678:android:a7aeac02f6fe07e6c6a6cf',
    messagingSenderId: '105046275678',
    projectId: 'spotify101',
    storageBucket: 'spotify101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtBgvKReoEqmISNfhR_YYx4nz2bb7BgZ0',
    appId: '1:105046275678:ios:b652a840099cfc38c6a6cf',
    messagingSenderId: '105046275678',
    projectId: 'spotify101',
    storageBucket: 'spotify101.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtBgvKReoEqmISNfhR_YYx4nz2bb7BgZ0',
    appId: '1:105046275678:ios:b652a840099cfc38c6a6cf',
    messagingSenderId: '105046275678',
    projectId: 'spotify101',
    storageBucket: 'spotify101.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNuEYEmyPqa-2XNA_cHab1FGXMXrAwqkY',
    appId: '1:105046275678:web:0886bd95a352940ac6a6cf',
    messagingSenderId: '105046275678',
    projectId: 'spotify101',
    authDomain: 'spotify101.firebaseapp.com',
    storageBucket: 'spotify101.appspot.com',
  );
}
